#!/bin/bash
echo "=== Wheelpedia Indonesia - Deploy ==="
echo ""
echo "1. Setup Database (Supabase)"
echo "   - Buka https://supabase.com"
echo "   - Buat project baru"
echo "   - Copy connection string ke .env"
echo ""
echo "2. Push Schema"
echo "   npx prisma db push"
echo ""
echo "3. Seed Data"
echo "   node prisma/seed.js"
echo ""
echo "4. Deploy ke Vercel"
echo "   vercel --prod"
echo ""
echo "Selesai!"
